export const termsHEB = {
  hasOpenRequest: 'ישנה בקשה פתוחה',
  customer: 'לקוח',
  mobile: 'נייד',
  email: 'אימייל',
  username: 'שם',
  signIn: 'התחבר',
  confirmPassword: 'אימות סיסמא',
  signUp: 'הירשם',
  doesNotMatchPassword: "סיסמאות לא תואמות",
  password: 'סיסמא',
  updateInfo: 'עדכון פרטים',
  changePassword: 'שינוי סיסמא',
  hello: 'היי',
  invalidOperation: 'פעולה לא חוקית',
  admin: 'אדמין',
  manager: 'מנהלת',
  disabled: 'מבוטל',
  yes: 'כן',
  no: 'לא',
  ok: 'אישור',
  areYouSureYouWouldLikeToDelete: 'בטוח למחוק',
  cancel: 'ביטול',
  home: 'home',
  userAccounts: 'משתמשים',
  invalidSignIn: 'פרטי כניסה שגויים',
  userDisabled: 'משתמש זה אינו פעיל',
  signOut: 'התנתק',
  resetPassword: 'אפס סיסמא',
  passwordDeletedSuccessful: 'סיסמא אופסה',
  passwordDeleteConfirmOf: 'בטוח לאפס סיסמא',
  rememberOnThisDevice: 'סכור אותי במכשיר זה?',
  RTL: false,


  greeting: (userName: string) => `שלום ${userName}! ברוך הבא למערכת בקשות המשכנתה. כיצד אוכל לעזור לך?`,
  mainMenu: `1. בקשה חדשה למשכנתה\n2. מחזור משכנתה\n3. בדיקת סטטוס בקשה קיימת\n4. יצירת קשר עם נציג\nאנא השב עם מספר האפשרות הרצויה (1-4)`,
  unrecognizedInput: `תודה על פנייתך. לא הצלחתי להבין את בקשתך. אנא כתוב "שלום" או "מעוניין במשכנתה" כדי להתחיל.`,
  existingRequestFound: (requestId: string, statusCaption: string, link: string, userName: string) =>
    `שלום ${userName}! נראה שיש לך בקשה קיימת שעדיין בטיפול (מספר: ${requestId}, סטטוס: ${statusCaption}).\nתוכל להמשיך לטפל בה או להעלות מסמכים דרך הקישור:\n${link}\nאם ברצונך לפתוח בקשה חדשה או לחזור לתפריט, אנא כתוב "התחל מחדש".`,
  newMortgageRequestPrompt: (link: string) => `מצוין! בחרת ב"בקשה חדשה למשכנתה". אנא מלא את פרטי הבקשה שלך בקישור הבא:\n${link}\nאנו נעדכן אותך בסטטוס הטיפול לאחר השליחה.`,
  refinanceRequestPrompt: (link: string) => `בחרת ב"מחזור משכנתה". אנא מלא את פרטי הבקשה שלך בקישור הבא:\n${link}\nאנו נעדכן אותך בסטטוס הטיפול לאחר השליחה.`,
  statusCheckPrompt: `בחרת ב"בדיקת סטטוס בקשה קיימת". אנא הזן את מספר תעודת הזהות שלך או את מספר הבקשה אם קיים.`,
  contactAgentPrompt: `בחרת ב"יצירת קשר עם נציג". נציג שלנו יחזור אליך בהקדם. אנא המתן בסבלנות.`,
  invalidOption: `בחירה לא חוקית. אנא השב עם מספר האפשרות הרצויה (1-4).`,
  requestNotFound: `לא נמצאה בקשה עם המזהה שסיפקת. אנא וודא שהזנת מספר תעודת זהות נכון, או מספר בקשה אם קיים.`,
  invalidIdFormat: `הזנת מספר זיהוי לא תקין. אנא הזן מספר תעודת זהות או מספר בקשה תקין.`,
  uploadDocumentsReminder: (link: string) => `אנא השלם את הבקשה דרך הקישור: ${link}\nאם השלמת, נוכל להמשיך בטיפול. תוכל לכתוב "התחל מחדש" כדי לחזור לתפריט הראשי.`,
  agentContactPending: `פנייתך לנציג עדיין ממתינה. אנו נעשה את מירב המאמצים לחזור אליך בהקדם.`,
  backToMainMenu: `חוזרים לתפריט הראשי. כיצד אוכל לעזור לך?`,
  errorHandler: `אנו מתנצלים על התקלה. אנא נסה שוב או כתוב "התחל מחדש" כדי לאפס את השיחה.`,
  directInputError: (link: string) => `נראה שאתה מנסה להזין פרטים ישירות. אנא השתמש בקישור למילוי הבקשה:\n${link}\nאו כתוב "התחל מחדש" כדי לחזור לתפריט הראשי.`,
  unhandledStateFallback: `אני מנסה להבין את בקשתך. אנא נסה שוב או כתוב "שלום" כדי להתחיל מחדש.`,
  invalidNewMortgageFormat: `נראה שהפורמט אינו תקין. אנא ספק את שמך המלא ואת סכום המשכנתה המבוקש בפורמט: *שם מלא, סכום (לדוגמה: משה כהן, 1000000)*`,
  invalidRefinanceFormat: `נראה שהפורמט אינו תקין. אנא ספק את סוג המשכנתה הנוכחית וסכום יתרת החוב בפורמט: *סוג המשכנתה, יתרת חוב (לדוגמה: צמוד מדד, 300000)*`,

}
